  version: '3.7'
  services:
    elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
      logging:
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "100m"
      environment:
        - "node.name=elasticsearch"
        - "discovery.type=single-node"
        - "bootstrap.memory_lock=true"
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "http.cors.enabled=true"
        - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
        - "xpack.security.enabled=false"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      networks:
        - elastic

    kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:8.13.3
      logging:
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "100m"
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ports:
        - "5601:5601"
      networks:
        - elastic

  networks:
    elastic:
      driver: bridge

  volumes:
    esdata:
      driver: local
